import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{createClient}from'@supabase/supabase-js';
import{Plus,Printer,Search}from'lucide-react';
import'./styles/main.css';

const TECHS=['Jordan','Alfie'];
const RAMPS=['Left','Middle','Right'];
const RC={Left:'left',Middle:'middle',Right:'right'};
const STATUS={booked:'Booked',arrived:'Arrived',in_progress:'In Progress',work_complete:'Work Complete',ready_to_invoice:'Ready to Invoice',archived:'Archived',no_show:'No-show'};
const JT=[['MOT',1],['Interim Service',1.5],['Minor Service',1.5],['Major Service',2.5],['Diagnostics',2],['Front Brakes',1.5],['Rear Brakes',1.5],['Front & Rear Brakes',3],['Suspension',2],['Clutch',6],['Timing Belt',4.5],['Turbo',5],['Air Conditioning',1],['Tyres',1],['Electrical',2],['Other',1]];
const supabaseUrl=import.meta.env.VITE_SUPABASE_URL;
const supabaseKey=import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;

function uid(){return Math.random().toString(36).slice(2,10)}
function todayISO(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}
function addDaysISO(iso,days){const d=new Date(`${iso}T00:00:00`);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function monthStartISO(iso){const d=new Date(`${iso}T00:00:00`);d.setDate(1);return d.toISOString().slice(0,10)}
function fd(iso){return new Date(`${iso}T00:00:00`).toLocaleDateString('en-GB',{weekday:'long',day:'2-digit',month:'short',year:'numeric'})}
function sd(iso){return new Date(`${iso}T00:00:00`).toLocaleDateString('en-GB',{weekday:'short',day:'2-digit',month:'short'})}
function wk(iso){const x=new Date(`${iso}T00:00:00`).getDay();return x===0||x===6}
function k(d){return`vecta:v1:${d}`} function kg(){return'vecta:v1:global'} function kt(){return'vecta:v1:tasks'}
function ld(d){return JSON.parse(localStorage.getItem(k(d))||'[]')} function sdj(d,j){localStorage.setItem(k(d),JSON.stringify(j))}
function lg(){return JSON.parse(localStorage.getItem(kg())||'[]')} function sg(j){localStorage.setItem(kg(),JSON.stringify(j))}
function lt(){return JSON.parse(localStorage.getItem(kt())||'[]')} function st(t){localStorage.setItem(kt(),JSON.stringify(t))}

async function seed(){if(supabase)return;let t=todayISO();if(!localStorage.getItem(k(t)))sdj(t,[{id:uid(),card_type:'job',booking_date:t,registration:'YD18 ABC',vehicle:'Ford Transit',work_required:'Rear brakes',drop_time:'08:30',technician:'Alfie',ramp:'Left',status:'booked',job_type:'Rear Brakes',estimated_hours:1.5},{id:uid(),card_type:'job',booking_date:t,registration:'MJ20 CCC',vehicle:'Nissan Juke',work_required:'Diagnostic',drop_time:'12:00',technician:'Jordan',ramp:'Middle',status:'in_progress',job_type:'Diagnostics',estimated_hours:2}]);if(!localStorage.getItem(kg()))sg([{id:uid(),card_type:'job',registration:'AB12 XYZ',vehicle:'Nissan Qashqai',work_required:'Service + MOT',drop_time:'10:30',technician:'Unallocated',status:'booked',job_type:'Minor Service',estimated_hours:2},{id:uid(),card_type:'waiting',registration:'KV70 UOS',vehicle:'BMW 218i',work_required:'Brake reset when there is a gap',technician:'Waiting',status:'booked',job_type:'Diagnostics',estimated_hours:1}]);if(!localStorage.getItem(kt()))st([{id:uid(),task_text:'Ring customer about Qashqai',priority:'urgent',done:false},{id:uid(),task_text:'Invoice Transit brakes',priority:'today',done:false}])}
async function listDate(d){if(supabase){let{data,error}=await supabase.from('jobs').select('*').eq('booking_date',d).eq('archived',false).neq('technician','Unallocated').neq('card_type','waiting').order('drop_time');if(error)throw error;return data||[]}return ld(d).filter(j=>!j.archived&&j.technician!=='Unallocated'&&j.card_type!=='waiting')}
async function listGlobal(){if(supabase){let{data,error}=await supabase.from('jobs').select('*').is('booking_date',null).eq('archived',false).order('created_at',{ascending:false});if(error)throw error;return data||[]}return lg().filter(j=>!j.archived)}
async function listTasks(){if(supabase){let{data,error}=await supabase.from('tasks').select('*').eq('done',false).order('sort_order');if(error)throw error;return data||[]}return lt().filter(t=>!t.done)}
async function saveJob(job,currentDate){let p={...job,registration:(job.registration||'').toUpperCase()};if(p.status==='archived')p.archived=true;if(p.technician==='Unallocated'||p.card_type==='waiting')p.booking_date=null;else p.booking_date=p.booking_date||currentDate;if(supabase){let{error}=await supabase.from('jobs').upsert(p);if(error)throw error;return}for(let key of Object.keys(localStorage)){if(key.startsWith('vecta:v1:')&&key!==kg()&&key!==kt()){let d=key.replace('vecta:v1:','');sdj(d,ld(d).filter(j=>j.id!==p.id))}}sg(lg().filter(j=>j.id!==p.id));if(p.booking_date)sdj(p.booking_date,[...ld(p.booking_date),p]);else sg([...lg(),p])}
async function deleteJob(id){if(supabase){let{error}=await supabase.from('jobs').delete().eq('id',id);if(error)throw error;return}for(let key of Object.keys(localStorage)){if(key.startsWith('vecta:v1:')){let rows=JSON.parse(localStorage.getItem(key)||'[]');localStorage.setItem(key,JSON.stringify(rows.filter(r=>r.id!==id)))}}}
async function saveTask(t){if(supabase){let{error}=await supabase.from('tasks').upsert(t);if(error)throw error;return}st([...lt().filter(x=>x.id!==t.id),t])}
async function deleteTask(id){if(supabase){let{error}=await supabase.from('tasks').delete().eq('id',id);if(error)throw error;return}st(lt().filter(t=>t.id!==id))}

function Util({dates}){return <section className="util">{dates.map(d=>{let jobs=ld(d).filter(j=>!j.archived),hrs=jobs.reduce((s,j)=>s+Number(j.estimated_hours||1),0),pct=Math.min(140,Math.round((hrs/18)*100));return <button key={d} className={`utilDay ${wk(d)?'closed':pct>95?'red':pct>75?'amber':'green'}`}><b>{sd(d)}</b><span>{wk(d)?'Closed':pct+'%'}</span>{!wk(d)&&<div><i style={{width:Math.min(100,pct)+'%'}}/></div>}</button>})}</section>}
function Card({job,onEdit,onDragStart}){return <div className={`job ${RC[job.ramp]||''} ${job.status}`} draggable onDragStart={e=>onDragStart(e,job)} onDoubleClick={()=>onEdit(job)}>{job.drop_time&&<div className="time">{String(job.drop_time).slice(0,5)}</div>}<b>{job.registration||'NO REG'}</b><span>{job.vehicle}</span><p>{job.work_required}</p><em>{STATUS[job.status]||job.status}</em></div>}
function Dialog({job,date,onClose,onSave,onDelete}){const[form,setForm]=useState(job||{});useEffect(()=>setForm(job||{id:'',card_type:'job',registration:'',vehicle:'',work_required:'',customer_note:'',drop_time:'',technician:'Unallocated',ramp:'',status:'booked',job_type:'Other',estimated_hours:1}),[job]);function u(f,v){if(f==='registration')v=v.toUpperCase();if(f==='job_type'){let found=JT.find(([n])=>n===v);setForm(x=>({...x,job_type:v,estimated_hours:found?found[1]:x.estimated_hours}));return}setForm(x=>({...x,[f]:v}))}return <div className="backdrop"><div className="dialog"><h2>{form.id?'Edit Job':'Add Job'}</h2><div className="two"><label>Card Type<select value={form.card_type||'job'} onChange={e=>u('card_type',e.target.value)}><option value="job">Job</option><option value="waiting">Waiting Job</option></select></label><label>Status<select value={form.status||'booked'} onChange={e=>u('status',e.target.value)}>{Object.entries(STATUS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><label>Registration<input autoFocus value={form.registration||''} onChange={e=>u('registration',e.target.value)}/></label><label>Vehicle<input value={form.vehicle||''} onChange={e=>u('vehicle',e.target.value)}/></label><label>Work Required<textarea value={form.work_required||''} onChange={e=>u('work_required',e.target.value)}/></label><div className="two"><label>Job Type<select value={form.job_type||'Other'} onChange={e=>u('job_type',e.target.value)}>{JT.map(([n])=><option key={n}>{n}</option>)}</select></label><label>Estimated Hours<input type="number" step="0.5" value={form.estimated_hours||1} onChange={e=>u('estimated_hours',Number(e.target.value))}/></label></div><div className="two"><label>Drop-off<input type="time" va