import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {parseHTML} from 'linkedom';
const src=readFileSync(new URL('../../public/js/haynes-job-tools.js',import.meta.url),'utf8');
const module=src.slice(src.indexOf('/* Dashboard registration lookup:'));
function setup(fetch){const {window,document}=parseHTML('<html><body><header class="top"><h1>Dashboard</h1><div class="plannerGlobalSearchWrap"></div></header></body></html>');const create=document.createElement.bind(document);document.createElement=n=>{const el=create(n);if(n==='dialog')el.showModal=()=>{};return el;};window.fetch=fetch;window.VectaHaynesJobTools={remember:v=>v,vehicleLink:()=> 'https://www.workshopdata.com/touch/site/layout/modelDetail?typeId=t_123',safeImage:()=>''};let preset;window.openJobModal=(id,p)=>preset=p;vm.runInNewContext(module,{window,document,AbortController,URLSearchParams,setTimeout,Date});window.VectaHaynesDashboardLookup.install();return {window,document,preset:()=>preset};}
const vehicle={registration:'FX69XWU',make:'Nissan',model:'Qashqai',variant:'Diesel',typeId:'t_123'};
test('lookup plate sits before global search and starts blank',()=>{const {document}=setup(()=>{});const form=document.getElementById('haynesDashboardLookup');assert.equal(form.nextElementSibling.className,'plannerGlobalSearchWrap');assert.equal(form.querySelector('input').value,'');assert.match(form.textContent,/GB/);});
test('matched lookup opens quote form with unallocated vehicle and no automatic save',async()=>{const {window,document,preset}=setup(async url=>({ok:true,json:async()=>url.includes('haynes-vehicle')?{status:'MATCHED',vehicle}:{registration:'FX69XWU'}}));await window.VectaHaynesDashboardLookup.open('fx69 xwu');const page=document.getElementById('haynesLookupPage');const form=page.querySelector('form');form.elements={mileage:{value:'120000'}};page.querySelector('[data-create="quote"]').onclick();assert.equal(preset().status,'quote');assert.equal(preset().registration,'FX69XWU');assert.equal(preset().mileage,120000);assert.equal(preset().technician,'Unallocated');assert.equal(document.getElementById('haynesLookupPage'),null);});
test('mismatched vehicle cannot enable creation buttons',async()=>{const {window,document}=setup(async()=>({ok:true,json:async()=>({status:'MATCHED',vehicle:{...vehicle,registration:'OTHER'}})}));await window.VectaHaynesDashboardLookup.open('FX69 XWU');assert.match(document.querySelector('[data-status]').textContent,/unavailable/);assert.equal(document.querySelector('[data-create]').hasAttribute('disabled'),true);});
