import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {parseHTML} from 'linkedom';
const source=fs.readFileSync(new URL('../../public/js/vecta-fleet-images.js',import.meta.url),'utf8');
const url='https://www.haynespro-assets.com/workshop/images/319004648.svgz';
function setup(vehicles,tools={},saved=true,offscreen=false){const {window}=parseHTML('<html><body>'+vehicles.map(v=>'<button data-fleet-image="'+v.id+'"></button>').join('')+'</body></html>');for(const cell of window.document.querySelectorAll('[data-fleet-image]'))cell.getBoundingClientRect=()=>({top:offscreen?1200:10,bottom:offscreen?1240:50,width:100,height:40});let observer;let calls=0;const root={innerHeight:800,__vectaFleetState:()=>({vehicles,save:async()=>{calls++;return saved},render:()=>{}}),VectaHaynesJobTools:{safeImage:x=>x===url?x:'',...tools}};vm.runInNewContext(source,{window:root,document:window.document,MutationObserver:class{constructor(callback){observer=callback}observe(){}},setTimeout,queueMicrotask});return {api:root.VectaFleetImages,document:window.document,calls:()=>calls,root,observe:records=>observer(records)};}
test('matched Haynes images render via live state bridge, with colour preserved',async()=>{const v={id:'internal',fleetGroup:'Nissan Internal',model:'Qashqai'};const {api,document,calls}=setup([v],{genericImage:()=>({imageUrl:url})});assert.equal(document.querySelector('img').src,url);assert.equal(document.querySelector('svg'),null);await api.saveColour('internal','Blue');api.mount();assert.equal(calls(),1);assert.equal(document.querySelector('img').dataset.colour,'Blue');});
test('road vehicle lookup populates the same-model internal image without looking up an internal registration',async()=>{const regs=[];const vehicles=[{id:'internal',fleetGroup:'Nissan Internal',registration:'MTC 2',model:'NV 200'},{id:'pool',fleetGroup:'Nissan Pool Cars',registration:'VN68 FPJ',model:'NV200'}];const {document}=setup(vehicles,{lookup:async reg=>{regs.push(reg);return {imageUrl:url}}});await new Promise(r=>setTimeout(r,10));assert.deepEqual(regs,['VN68 FPJ']);assert.equal(document.querySelectorAll('img').length,2);});
test('unmatched on-site equipment never shows fabricated drawings or triggers a registration lookup',async()=>{let lookups=0;const {document}=setup([{id:'internal',fleetGroup:'Nissan Internal',registration:'TCS 1',model:'Golf Buggy'}],{lookup:async()=>{lookups++}});await new Promise(r=>setTimeout(r,10));assert.equal(lookups,0);assert.equal(document.querySelector('svg,img'),null);assert.match(document.body.textContent,/No Haynes image/);});
test('colour writes reject pool vehicles and invalid values and report cloud failure',async()=>{const vehicles=[{id:'internal',fleetGroup:'Nissan Internal',model:'Leaf'},{id:'pool',fleetGroup:'Nissan Pool Cars',model:'Leaf'}];const {api,calls}=setup(vehicles,{},false);await assert.rejects(api.saveColour('pool','Blue'));await assert.rejects(api.saveColour('internal','invalid'));assert.equal(calls(),0);await assert.rejects(api.saveColour('internal','Green'),/has not synced/);assert.equal(vehicles[0].colour,'Green');});
test('contact email is inserted in all three list variants using the inherited email resolver',()=>{const html=fs.readFileSync(new URL('../../index.html',import.meta.url),'utf8');assert.match(html,/function fleetContactEmailCell\(v\)\{var email=fleetEffectiveContactEmail\(v\)/);const body=html.slice(html.indexOf('function fleetMaintenanceHtml(){'),html.indexOf('function fleetHtml()'));assert.equal((body.match(/fleetContactEmailCell\(v\)/g)||[]).length,3);assert.match(body,/<span>Fleet \/ customer<\/span><span>Contact email<\/span><span>/);});
test('internal picker button stays on row one and image assets are cache-versioned',()=>{const css=fs.readFileSync(new URL('../../public/js/vecta-fleet-images.css',import.meta.url),'utf8');assert.match(css,/\.fleetPanel \.fleetRow\.due30Columns>\*\{grid-row:1\}/);const build=fs.readFileSync(new URL('../../scripts/split-built-html.mjs',import.meta.url),'utf8');assert.match(build,/'vecta-fleet-images.js','vecta-fleet-images.css'/);});

test('offscreen Fleet rows do not start Haynes lookups or repaint until visible',async()=>{let lookups=0;const {api,document}=setup([{id:'road',model:'Leaf',registration:'NK75BBX'}],{lookup:async()=>{lookups++;return null}},true,true);await new Promise(r=>setTimeout(r,10));const cell=document.querySelector('[data-fleet-image]');api.mount();assert.equal(cell.children.length,0);assert.equal(lookups,0);cell.getBoundingClientRect=()=>({top:20,bottom:60,width:100,height:40});api.mount();await new Promise(r=>setTimeout(r,10));assert.equal(lookups,1);assert.match(cell.textContent,/No Haynes image/);});
test('unrelated mutations and image painting do not schedule a Fleet rescan',async()=>{let snapshots=0;const {document,observe}=setup([{id:'road',model:'Leaf',registration:'NK75BBX'}],{snapshot:()=>{snapshots++;return {imageUrl:url}}});const before=snapshots;const unrelated=document.createElement('p');observe([{target:document.body,addedNodes:[unrelated]}]);const cell=document.querySelector('[data-fleet-image]');observe([{target:cell,addedNodes:[cell.querySelector('img')]}]);await new Promise(r=>setTimeout(r,130));assert.equal(snapshots,before);});
test('repeated mounts reuse artwork without rewriting local storage',()=>{let writes=0;const {api,root}=setup([{id:'road',model:'Leaf',registration:'NK75BBX'}],{snapshot:()=>({imageUrl:url})});root.localStorage={setItem:()=>writes++};api.mount();api.mount();assert.equal(writes,0);});
